= eXo Release Manager Catalog

This repository contains all JSON files used by the *eXo Release Manager* bot to do the releases.

== Files organization

* +exo-platform+: folder for JSON files related to releases of all PLF components and all supported Add-ons
* +exo-tribe+: folder for JSON files related to releases of all eXo Tribe components and add-ons
* +samples+ : samples JSON files to test the Release Manager

== Example of JSON Catalog

The JSON catalog file is created with the help of:
* the *JIRA description about projects to release*
* the eXo Components diagram to be aware of Maven dependencies

[source,json]
.JSON Catalog example
----
...

{
     "name":"wiki",  <1>
     "git_organization":"exoplatform",    <2>
     "labels":"plf",   <3>
     "maven_property_version":"org.exoplatform.wiki.version",   <4>
     "container": {
       "image": "exoplatform/release:jdk8-maven32",    <5>
       "step": 6        <6>
     },
     "release":{
        "branch":"develop",     <7>
        "version":"4.4.0-M06",    <8>
        "current_snapshot_version":"4.4.x-SNAPSHOT",    <9>
        "next_snapshot_version":"4.4.x-SNAPSHOT",     <10>
        "patches":"",     <11>
        "patches_after_release":"",    <12>
        "nexus_host":"exoplatform",     <13>
        "nexus_staging_profile":"public"   <14>
     }
  },
  {
     "name":"social",
     "git_organization":"exoplatform",
     "labels":"plf",
     "maven_property_version":"org.exoplatform.social.version",
     "container": {
       "image": "exoplatform/release:jdk8-maven32",
       "step": 5
     },
     "release":{
        "branch":"develop",
        "version":"4.4.0-M06",
        "current_snapshot_version":"4.4.x-SNAPSHOT",
        "next_snapshot_version":"4.4.x-SNAPSHOT",
        "patches":"",
        "patches_after_release":"",
        "nexus_host":"exoplatform",
        "nexus_staging_profile":"public"
     }
  },
...
----
<1> *GitHub* project name
<2> *GitHub* organization to used
<3> *NOT USED for now* (will be use to build projects by category instead of given all projects names to the process)
<4> *Maven property* to find in Maven POMs of *others projects* which depends on this project (in order to replace the SNAPSHOT version by the RELEASE one)
<5> *eXo Docker Image* to use to build and release the project (be careful of the Maven and JDK stack)
<6> *NOT USED for now* (will be use to build projects in parallel if no maven dependencies between projects)
<7> *Git branch* to use for the basecode to build
<8> *Version to Release* for this project
<9> *Current version* of the project to replace in the POMs project *AND in projects which depends on it*
<10> *Next version* to set *in projects which depends on it*
<11> *NOT USED for now* (used by old release scripts, remove it?)
<12> *NOT USED for now* (used by old release scripts, remove it?)
<13> *Nexus Host* to use for the project
<14> *Nexus Staging Profile* to use for the project

[IMPORTANT]
The *Nexus Staging Profile*  is very important specially for Private and Private Trial projects.
